package on2018_04.on2018_04_07_Qualification_Round_2018.Saving_The_Universe_Again;

import net.egork.chelper.tester.NewTester;

import org.junit.Assert;
import org.junit.Test;

public class Main {
	@Test
	public void test() throws Exception {
		if (!NewTester.test("lib/test/on2018_04/on2018_04_07_Qualification_Round_2018/Saving_The_Universe_Again/Saving The Universe Again.task"))
			Assert.fail();
	}
}
