package on2013_01.on2013_01_16_Codeforces_Round__161.C___Circle_of_Numbers;

import net.egork.chelper.tester.NewTester;

import org.junit.Assert;
import org.junit.Test;

public class Main {
	@Test
	public void test() throws Exception {
		if (!NewTester.test("lib/test/on2013_01/on2013_01_16_Codeforces_Round__161/C___Circle_of_Numbers/C - Circle of Numbers.task"))
			Assert.fail();
	}
}
